#!/bin/sh

bspc config border_width        1
bspc config window_gap          12

bspc config bottom_padding	0
bspc config top_padding		10
bspc config left_padding	0
bspc config right_padding	0

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor HDMI-0 -d I II III IV
bspc monitor DVI-0 -d V VI VII VIII
bspc monitor DisplayPort-0 -d IX X XI XII

bspc rule -a Gimp follow=on floating=on # The GIMP
bspc rule -a mplayer2 floating=on # mplayer
bspc rule -a crx_chlffgpmiacpedhhbkiomidkjlcfhogd floating=on # PushBullet Quick-Reply (Chrome)
bspc rule -a feh floating=on # feh image viewer
bspc rule -a Browser floating=on # Firefox preferences window

panel &
stalonetray &
volumeicon &
fbsetbg /home/msweeney/walls/darkwood.png &
