#!/bin/sh

bspc config border_width        0
bspc config window_gap          20

bspc config bottom_padding	0
bspc config top_padding		0
bspc config left_padding	0
bspc config right_padding	0

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     false
bspc config focus_by_distance   true

bspc config focused_border_color '#00FF00'
bspc config normal_border_color '#FF0000'
bspc config active_border_color '#0000FF'

bspc monitor HDMI-0 -d I II III
bspc monitor DVI-0 -d IV V VI
bspc monitor DisplayPort-0 -d VII IIX IX

bspc rule -a Gimp follow=on floating=on # The GIMP
bspc rule -a mplayer2 floating=on # mplayer
bspc rule -a crx_chlffgpmiacpedhhbkiomidkjlcfhogd floating=on # PushBullet Quick-Reply (Chrome)
bspc rule -a feh floating=on # feh image viewer
bspc rule -a Browser floating=on # Firefox preferences window
bspc rule -a TeamViewer.exe floating=on # Teamviewer "Contacts" window.
bspc rule -a Steam floating=on # Steam. Obviously.
bspc rule -a pcmanfm floating=on # pcmanfm file manager.

panel &
stalonetray &
volumeicon &
fbsetbg -f /home/blind/walls/wallpaper-27083.jpg &

bspc config -d I top_padding 10
bspc config -d II top_padding 10
bspc config -d III top_padding 10
bspc config -d VIII window_gap 0
bspc desktop IV -l monocle
